### ISSUE TITLE
How to use a handler function

### ISSUE THREAD

**Issue by noel1973** [OvidijusParsiunas/deep-chat#101]
Hi @OvidijusParsiunas 

First I want to thank you for an excellent chat, this chat is really good

I need your assistance

I have the following code

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/42816090/22042e33-ad78-41ea-bc45-433ce87894d6)

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/42816090/4f287e74-50fd-44a3-af48-690f4132db53)

This code works well in VUE I can get the response back fine from an Azure function, but I'm not able to update the AI response on the chat using
:responseInterceptor="(response) => {                   
                    return { text: response.choices[0].message.content };
            }"  

Any ideas how I can solve this? I don't know if this is a bug

Thanks in advance.

**Comment by OvidijusParsiunas** [comment]
Hi @noel1973. I see you are using the [handler](https://deepchat.dev/docs/connect#Handler) function to handle your requests and have assigned it to a function called _fetchData_.

[handler](https://deepchat.dev/docs/connect#Handler) functions work using _signal_ calls. So you should set it as an argument: `fetchData(data, signals) {` and when you receive the request from your service - instead of _return_, you should use something like this `signals.onResponse({text: data.bot.choices[0].message.content})` and `signals.onResponse({error: error})`.
This is all documented [here](https://deepchat.dev/docs/connect#Handler) and you can watch this [video](https://www.youtube.com/watch?v=ySU7Tj99mbA&ab_channel=ovi) to help you.

Also, when using a [handler](https://deepchat.dev/docs/connect#Handler) function, you do not need the _url_ request property and [requestInterceptor](https://deepchat.dev/docs/interceptors#requestInterceptor)/[responseInterceptor](https://deepchat.dev/docs/interceptors#responseInterceptor) are optional as you can handle everything in the [handler](https://deepchat.dev/docs/connect#Handler).

Let me know if you have any other questions. Thanks.

**Comment by noel1973** [comment]
Hi @OvidijusParsiunas 

I found another way to do this

I just eliminated that function on the methods and do this instead

:responseInterceptor="async (response) => {            
                    const data = await response.json();       
                    return { text: data.bot };
            }"  

It works pretty well too :) but I follow your advice as well, thank you so much

**Comment by OvidijusParsiunas** [comment]
Ya, by looking at your code - you can do without the handler function :D

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue since the original problem has been resolved. If you have any further questions, you are more than welcome to create a new issue.

Thankyou!
