### ISSUE TITLE
next.js example  is not accessible in regions where OpenAI prohibits access

### ISSUE THREAD

**Issue by buzhou9** [OvidijusParsiunas/deep-chat#103]
OpenAI/chat.ts in the next.js example is not accessible in regions where OpenAI prohibits access, even if I have the proxy turned on. But I execute JS scripts in the terminal and it can be accessed normally。

Here's what I tested the script。
```
const axios = require('axios');

const axiosConfig = {
  headers: {
    'Content-Type': 'application/json',
    Authorization: 'Bearer openAIKey',
  }
};

axios.post(
  'https://api.openai.com/v1/chat/completions',
  {
    model: 'gpt-3.5-turbo',
    messages: [{ role: 'user', content: 'Say this is a test!' }],
  },
  axiosConfig
).then(res => {
  console.log(res.data)
}).catch(e => {
  console.error(e)
})

```

This is the “chat.ts ” file I rewrote and it works fine
```
import axios from 'axios'
import type { NextApiRequest, NextApiResponse } from 'next'
import {createReqChatBody} from "../../../utils/openAIChatBody";
import {DeepChatOpenAITextRequestBody} from "../../../types/deepChatTextRequestBody";


export default async function handle (req: NextApiRequest, res: NextApiResponse) {
  try {
    const axiosConfig = {
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
      }
    };
    const textRequestBody = (req.body) as DeepChatOpenAITextRequestBody;
    const chatBody = createReqChatBody(textRequestBody)
    console.log(chatBody)
    const response = await axios.post(
      'https://api.openai.com/v1/chat/completions',
      chatBody,
      axiosConfig
    )
    console.log(response.data);
    console.log(response.data.choices[0].message.content)
    res.json({text: response.data.choices[0].message.content})
  } catch (error) {
    res.status(500).json({ message: error.toString() })
  }
}

```

Why can't the agent I configure in the terminal not take effect in the fetch method of next.js?

**Comment by OvidijusParsiunas** [comment]
Hi @buzhou9. I'm sorry to hear you are having proxy issues.

First I want to clarify your problem statement; the first example works fine if you run it in the _terminal_, but the second _next.js_ example doesn't work?

May I ask what error are you getting in the second example and are you sure it is a proxy error?

If it is a proxy error, then the problem will largely depend on your pc/proxy setup and is unfortunately difficult for me to diagnose. However I can perhaps point you to areas to look at:

- First of all, try to call the `NextJs` API endpoints using the _terminal_ or a tool like [Postman](https://www.postman.com/product/tools/) to see if the error will still be there.
- You can also try to see if this is a problem for other Node frameworks like [Express](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/node/express) - you can try calling it via _terminal_/[Postman](https://www.postman.com/product/tools/)/[UI Project](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/ui). It may also be worth trying out the [Python/Flask](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/python/flask) server just to see if the proxy is not working with Node exclusively.
- If the error is still there then it has got to be something to do with your proxy configuration that only works in your terminal. Maybe there is some sort of a script that runs when you open up your terminal, it would perhaps also need to run before the NextJs server starts up, it is only a speculation but worth investigating.
- Finally, one thing to note is that you can always deploy the NextJs server via hosting platforms like [Vercel](https://vercel.com/) into regions that don't have the regional limitations, then you can call the endpoints from anywhere.
- One other thing you can try is developing in [cloud based environments](https://www.hongkiat.com/blog/cloud-ide-developers/) or even [SSH into a server](https://www.google.com/search?q=ec2+ssh+vscode&sca_esv=601059271&sxsrf=ACQVn081p7KMuBCPzz2_DNBO8QdN9TYbwA%3A1706099291309&ei=WwKxZba0EtnWhbIP0u65wAQ&ved=0ahUKEwj2zdaRg_aDAxVZa0EAHVJ3DkgQ4dUDCBA&uact=5&oq=ec2+ssh+vscode&gs_lp=Egxnd3Mtd2l6LXNlcnAiDmVjMiBzc2ggdnNjb2RlMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgsQABiABBiKBRiGA0jEVlDRAljvVXAFeACQAQOYAb8BoAHFGKoBBTE4LjEyuAEDyAEA-AEBqAIUwgIKEAAYRxjWBBiwA8ICChAjGIAEGIoFGCfCAgQQIxgnwgILEAAYgAQYigUYkQLCAgsQABiABBixAxiDAcICDhAuGIAEGLEDGMcBGNEDwgILEC4YgAQYxwEY0QPCAg4QABiABBiKBRixAxiDAcICChAAGIAEGIoFGEPCAhAQLhiABBiKBRhDGMcBGNEDwgILEC4YrwEYxwEYgATCAggQLhiABBixA8ICCxAuGIAEGMcBGK8BwgILEC4YgAQYsQMYgwHCAgUQLhiABMICBRAAGIAEwgIIEAAYgAQYsQPCAhoQLhivARjHARiABBiXBRjcBBjeBBjgBNgBAcICBxAuGIAEGArCAhEQLhiABBjHARivARiYBRiZBcICDhAuGIAEGMcBGK8BGJgFwgINEC4YQxixAxiABBiKBcICCxAuGIMBGLEDGIAEwgIHEAAYgAQYCsICHBAuGEMYsQMYgAQYigUYlwUY3AQY3gQY3wTYAQHCAg0QABiABBiKBRhDGMkDwgILEAAYgAQYigUYkgPCAhMQABiABBiKBRhDGLEDGIMBGMkDwgIQEAAYgAQYFBiHAhixAxiDAcICExAAGIAEGIoFGJECGLEDGEYY-QHCAhEQLhiABBixAxiDARjHARivAcICKhAAGIAEGIoFGJECGLEDGEYY-QEYlwUYjAUY3QQYRhj0Axj1Axj2A9gBAsICBxAjGOoCGCfCAhQQABiABBjjBBjpBBjqAhi0AtgBA8ICFhAAGAMYjwEY5QIY6gIYtAIYjAPYAQTCAhEQLhiDARjHARixAxjRAxiABMICERAuGIAEGLEDGIMBGMcBGNEDwgIREAAYgAQYigUYkQIYsQMYgwHCAhAQABiABBiKBRhDGLEDGIMB4gMEGAAgQYgGAZAGCLoGBggBEAEYFLoGBggCEAEYE7oGBggDEAEYAboGBggEEAEYCw&sclient=gws-wiz-serp) as these can be hosted in regions that are not blocked by OpenAI.

This is unfortunately as much advise I can give you as proxy issues are largely dependent on the setup of the proxy itself.
Furthermore, the scope of the problem is outside of the topic of Deep Chat, hence the information I can provide is limited.

**Comment by buzhou9** [comment]
Thank you for the suggestion. I'd like to try debugging locally。Both of the snippets I provided work fine, which is enough to prove that the agent is valid. The fetch method of next.js does not have server access through a proxy, which should be a problem with the next.js framework itself, which is indeed beyond the topic of deep-chat.
