### ISSUE TITLE
How to modify the baseURL in direct connection mode?

### ISSUE THREAD

**Issue by miaohaiwei** [OvidijusParsiunas/deep-chat#105]
I have tried this project and it is very useful. It has solved my problem. There is a **problem that I need to modify the baseURL in direct connection mode.** What should I do. The reason is that I used the server to proxy the chatGPT api service, so the base ULR of the chatGPT API has changed.

**Comment by OvidijusParsiunas** [comment]
Hi @miaohaiwei.

For custom endpoints we recommend using the [request](https://deepchat.dev/docs/connect#request) property which allows you to configure the exact connection settings you need for your target service.

Nevertheless, if you want to use the preconfigured settings in the [`directConnection`](https://deepchat.dev/docs/directConnection/) property and just change the url. You can do this by simply setting the `url` in the [`request`](https://deepchat.dev/docs/connect#request) property. E.g (syntax will need to be changed for your framework):
```
directConnection={{
  openAI: {
    chat: true,
    key: 'key-here'
  }
}}
request={{url: 'another-url'}}
```
This will build the request headers and the body according to the OpenAI standards and will call `'another-url'` instead of the default OpenAI API url.
To modify the headers and the outgoing body, you can also use the [`requestInterceptor`](https://deepchat.dev/docs/interceptors#requestInterceptor).

**Please note that the above solution will not work for all [`directConnection`](https://deepchat.dev/docs/directConnection/) services as some use multiple different urls to complete a call and we instead recommend devs to configure all their settings using [`request`](https://deepchat.dev/docs/connect#request)/[`requestInterceptor`](https://deepchat.dev/docs/interceptors#requestInterceptor) properties and ultimately use their own servers for production.**

Let me know if you have any questions.

**Comment by OvidijusParsiunas** [comment]
Since there has been no further communication I will be closing this issue.
You can still comment in regards to this topic below and for anything else feel free to raise a new issue. Thanks!
