### ISSUE TITLE
scroll down to bottom in angular

### ISSUE THREAD

**Issue by nima-cp** [OvidijusParsiunas/deep-chat#14]
Hello, thanks for this useful library.

I'm using it in Angular but when the page reloads I want to scroll down to the bottom  (I'm loading the chat history from db). I checked the repo and I encountered this:

```typescript
public static isScrollbarAtBottomOfElement(element: HTMLElement) {
    // Get the scroll height, visible height, and current scroll position
    const scrollHeight = element.scrollHeight;
    const visibleHeight = element.clientHeight;
    const scrollPosition = element.scrollTop;

    // Calculate the remaining scroll height
    const remainingScrollHeight = scrollHeight - visibleHeight;

    // Check if the current scroll position is at the bottom
    return scrollPosition >= remainingScrollHeight - ElementUtils.CODE_SNIPPET_GENERATION_JUMP;
  }
```

I tried to implement the same but it doesn't understand the container with id = messages. I'd appreciate if you could help me.

here's my component

```typescript
  async ngOnInit(): Promise<void> {
    const chatHistory = await this.loadChatHistory();
    this.initialMessages.push(...chatHistory);

    // I want to scroll down here
  }
```

**Comment by OvidijusParsiunas** [comment]
Hi @nima-cp, thankyou for raising this issue. Just so I understand the context of this correctly, when `this.initialMessages.push(...chatHistory);` is executed - the messages are populated in the chat, but the scrollbar remains at the top?

**Comment by nima-cp** [comment]
Thank you so much for answering quickly. Yeah exactly it remain on top, the first msg.

here's the simplified version of my component:


```typescript
@Component({
  selector: 'cpx-header-chatbot',
  template: `
    <div class="input-group chat-container" [hidden]="!isChatOpen">
      <deep-chat
        [initialMessages]="initialMessages"
        [request]="{...}"
      ></deep-chat>
    </div>
  `,
  styles: [
    `
      deep-chat {
        display: flex;
        justify-content: center;
        border-radius: 10px;
        position: fixed;
        bottom: 0px;
        right: calc(82px + 1%);
        box-shadow: 0 0 128px 0 rgba(0, 0, 0, 0.1),
          0 32px 64px -48px rgba(0, 0, 0, 0.5);
        margin-bottom: 0.8rem;
      }
    `,
  ],
})
export class HeaderChatbotComponent implements AfterViewInit, OnInit {
  isChatOpen: boolean = false;

  ngAfterViewInit(): void {
    setTimeout(() => {
      this.navItemsService.addItems([
        {
          id: 'Chatbot',
          html: `<div class='chatbot-icon'><i class='fab fa-rocketchat fa-lg me-1'></i><span>${this.localizationService.instant(
            'ChatAI::Chatbot',
          )}</span></div>`,
          action: () => {
            this.toggleChatbot();
          },
          order: 1, // puts as first element
        },
      ]);
    }, 1);
  }

  initialMessages: ChatMessage[] = [];

  async ngOnInit(): Promise<void> {
    const chatHistory = await this.loadChatHistory();
    this.initialMessages = [
      {
        role: 'ai',
        text: this.localizationService.instant(
          'ChatAI::ChatbotComponent:WelcomeMessage',
        ),
        createdAt: new Date().toISOString(),
      },
    ];
    this.initialMessages.push(...chatHistory);
  }

  async loadChatHistory() {
    return new Promise<ChatMessage[]>((resolve) => {
      this.actions.getChatHistory().subscribe((response: any) => {
        const chatHistory: ChatMessage[] = response.history;
        resolve(chatHistory);
      });
    });
  }

  toggleChatbot() {
    this.isChatOpen = !this.isChatOpen;
  }
}
```

**Comment by OvidijusParsiunas** [comment]
Thankyou for sharing your code.

**Reason why this is happening:**
I am not sure when the `toggleChatbot` function is executed, but assuming that `initialMessages` get populated before it is called, the chat would render the messages whilst it is still not visible (`hidden`) and attempt to scroll down, however because it is not visible it has no defined height to scroll down to hence the scrollbar is at the top. So when the chat is made visible after calling `toggleChatbot` - the chat displays the messages without any scrolling.

**You have a few options to fix this:**
- You can use `*ngIf="isChatOpen` instead of `[hidden]="!isChatOpen"`. What this does is instead of having the chat hidden and then making it visible - it renders the chat from scratch when `isChatOpen` is set to _true_. So when the messages are rendered - the chat can analyze the result height to scroll down to the appropriate dimension.
- If the above is not an option, you can instead overwrite the `initialMessages` value to cause the web component to refresh itself when made visible as:
```
toggleChatbot() {
    this.isChatOpen = !this.isChatOpen;
    this.initialMessages = [...this.initialMessages];
  }
```

Small suggestions for other improvements:

- ```this.initialMessages.push(...chatHistory);``` is a little risky when populating the initial messages. The reason for this is because the reference to `initialMessages` stays the same and Angular/Deep Chat may not recognise that the values inside it are different and not render the new messages. If it does not cause any issues I would advise to use ```this.initialMessages = chatHistory;``` instead.
- Unless you have the `ChatMessage` type defined in another component, you can simply import the prebuilt type that comes with Deep Chat as: ```import { MessageContent } from "deep-chat/dist/types/messages";``` and use it as ```initialMessages: MessageContent[] = [];```.
These are just minor suggestions and you don't need to use them :)

Future:

I understand that chat history can take time to load and plan to optimize this experience by add a new feature for displaying a loading animation in the chat whilst the history is loading. I am currently working on other features, but should be able to add it to the component in the next 2-3 weeks, so if something like that is useful for you - make sure check our latest updates.

**Comment by nima-cp** [comment]
Thank you so much for your time and useful tips. Right now That works fine and your suggestions completely make sense.
Wish you all the best.

**Comment by nima-cp** [comment]
Moreover, I'd like to if there's anything like the user can resize the chatbot, and also put a header or close btn in this library.

**Comment by OvidijusParsiunas** [comment]
I was initially considering the ability to control the chat's position/sizing as something that should be controlled by the parent application as it is something that strictly correlates with the parent's styling approaches. However your feedback is really appreciated and I will nevertheless add it to my last of future features. Though, because I have so many at the moment it is hard to predict when I will be able to get to the header open/close part, but keep track an eye on this repo to see all the latest updates.

I am also very glad to hear that the fix worked and if you experience any other issues, have questions or suggestions, you can always create new issues in this repo, thanks!

**Comment by OvidijusParsiunas** [comment]
The component has a new [`scrollToBottom`](https://deepchat.dev/docs/methods#scrollToBottom) method in version `1.3.11` which you can use to force it to scroll down.
