### ISSUE TITLE
Send the request without showing it

### ISSUE THREAD

**Issue by littlepenguin89106** [OvidijusParsiunas/deep-chat#163]
When I use `submitUserMessage`, the request is shown on the chat. 
How do I only show the response?

**Comment by OvidijusParsiunas** [comment]
Hi @littlepenguin89106.
Please see the following issue where this question was already answered:
https://github.com/OvidijusParsiunas/deep-chat/issues/143

Thanks!

**Comment by littlepenguin89106** [comment]
I think its behaviour is different, because it doesn't trigger the `onNewMessage` event.

**Comment by OvidijusParsiunas** [comment]
The `onNewMessage` has no relevance to how the messages are displayed. You need to use the [`messageStyles`](https://deepchat.dev/docs/messages/styles/#messageStyles) property to set the styling via [this](https://github.com/OvidijusParsiunas/deep-chat/issues/143#issuecomment-1986872808) comment.

If your question is different, please elaborate. Thankyou.

**Comment by littlepenguin89106** [comment]
Thanks for replies,
I try to implement two requirements:
1. click the button1, send the request, user request and ai reply are all displayed
2. click the button2, send the request, only the ai reply is displayed

**Comment by OvidijusParsiunas** [comment]
Deep Chat does not provide the ability to have dynamic properties, so [`messageStyles`](https://deepchat.dev/docs/messages/styles/#messageStyles) can't be changed depending on the button that you clicked. 

The only advice I can offer here is instead of using [`submitUserMessage`](https://deepchat.dev/docs/methods#submitUserMessage) for button2 - you should try to use the `_addMessage` method. This is a method that is not part of our official documentation and will be added to the main API on our next release, however it is still available in the current release. The way it works is it accepts a [`Response`](https://deepchat.dev/docs/connect#Response) object as an argument and adds a message to the chat. E.g. `deepChatRef._addMessage({text: 'hello'});`.

The way you can use this in your use-case is you can process the request yourself on button2 click and then add the result to the chat via `_addMessage`. Hopefully this helps you.

**Comment by littlepenguin89106** [comment]
Got it! Thank you for the timely support.
