### ISSUE TITLE
Using input capture method for camera

### ISSUE THREAD

**Issue by anup-singh** [OvidijusParsiunas/deep-chat#172]
Is there any option to directly use camera on mobile devices instead of using getUserMedia.
HTML allows us to directly use mobile camera instead of getUsetMedia

For example - 
`<input type="file" name="image" accept="image/*" capture="user">`

reference - 
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture

**Comment by OvidijusParsiunas** [comment]
Hi @anup-singh.

The [images](https://deepchat.dev/docs/files#images) button is using the [input](https://www.w3schools.com/html/html_form_attributes.asp) element, however it doesn't use the [capture](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture) attribute. Nevertheless I have tested this button on my phone and upon clicking it I do get the camera option and I can switch between different modes (front/back), hence this does not seem to be problematic on that end.

The [camera](https://deepchat.dev/docs/files#camera) button on the other hand as you described does use the [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) method. The reason why we use it over the [input](https://www.w3schools.com/html/html_form_attributes.asp) button is because it gives us more control over the captured image when used on the browser to allow it to fit the modal and preview the captured image. Additionally it still does capture the camera on the phone (though it does not automatically use the back camera), so its a win-win.

If you want your users to have full control of the camera in mobile devices I would suggest that you would try the [images](https://deepchat.dev/docs/files#images) button instead.

Thankyou!

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue as there has been no further activity.

**Comment by elfar** [comment]
Hi Ovidijus,

I have not been able to use the "back" camera in any way on my Samsung phone.

 - images: there was a recent change in Android 14 which blocks the option to get input from the camera itself, only the album will work (https://stackoverflow.com/questions/77886145/chrome-on-android-14-does-not-show-the-option-to-open-the-camera-when-uploading) - unless one adds "capture" (https://gist.github.com/danawoodman/4788404bc620d5392d111dba98c73873)
 - camera: there is no toggle button in the camera view nor option to set constrain facingMode:environment for the getUserMedia

Any plans to change either/both of these? And continue your excellent work on this project!
