### ISSUE TITLE
Sending speech to text input

### ISSUE THREAD

**Issue by FranzHell** [OvidijusParsiunas/deep-chat#176]
Dear @OvidijusParsiunas

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/30411532/bcfa2b3c-9bbd-4f06-9b1c-73fdb5bc858c)
Can not send the text to speech input (send icon not clickable) .. only clickable when i add another character.

doesnt work here nor in a local running setup.
https://deepchat.dev/docs/speech/#speechToText

Can you help?

**Comment by OvidijusParsiunas** [comment]
Hi @FranzHell.
This issue has been fixed in the Deep Chat dev packages and will be part of our next release.

Due to my current work obligations and the next release being really big, it will take some time for it to go, hence I would recommend you to use our dev packages in the meanwhile. They are called `deep-chat-dev` and `deep-chat-react-dev` and behave just like the main packages except their names are different. They also contain a few property name changes, such as the [request](https://deepchat.dev/docs/connect#request) property is changed to `connect` and [stream](https://deepchat.dev/docs/connect#stream) is moved to the connect object. All of the current/old properties will still keep working as usual except you will see warnings in the console for their deprecation and get a few TypeScript warnings which you can ignore.

Let me know if this helps.
Thanks!
