### ISSUE TITLE
Feature Request: Add support for rendering mathematical symbols using katex or mathjax 

### ISSUE THREAD

**Issue by ZYPX** [OvidijusParsiunas/deep-chat#196]
Would love to have math expressions rendered dynamically in messages. I attempted to add this myself but was not successful.

Some available libraries are https://www.mathjax.org/ and https://katex.org/

Currently math from the LLM gets outputted like this:
![exampleMath](https://github.com/OvidijusParsiunas/deep-chat/assets/63077890/2b21b5d3-22bd-448a-b47f-65a29a1709fc)

I would like the output to be like this:
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/63077890/8c7cdf15-5034-48ba-b4f9-de6f5cc15194)

**Comment by OvidijusParsiunas** [comment]
Hi @ZYPX.

Because Deep Chat uses a library called [Remarkable](https://github.com/jonschlinkert/remarkable) to render its text content, the formatting is limited by its capabilities.

Unfortunately due to this, I would either recommend forking/cloning the repository and editing the component yourself ([steps here](https://www.npmjs.com/package/deep-chat#construction_worker-to-create-your-own-deep-chat-component)) or rendering the responses yourself via the `html` message responses (more info can be found [here](https://deepchat.dev/docs/messages/HTML)).

If another way to do this is found, you can re-open this issue and inform me of the changes that can be made. However, for now I will keep this issue closed.

Thankyou!
