### ISSUE TITLE
Customizing Dialogue Values

### ISSUE THREAD

**Issue by delsoul6104** [OvidijusParsiunas/deep-chat#199]
Currently, I want to achieve the following: when the user sends the dialogue "start", 
it will enter dialogue mode. At this point, a ConversationID will be generated. 
Throughout the conversation, in addition to the text, the ConversationID and channelID will also be sent to the backend.
 Currently, if there are suggestion buttons during the conversation, clicking the button essentially sends the button text. 
At this time, the ConversationID and channelID also need to be sent together. 
How can this be implemented?

 Thank you.

**Comment by OvidijusParsiunas** [comment]
Hi @delsoul6104.

The scope of this issue seems too broad and more closely related to your particular project so I won't be able to provide any particular code examples. However, by reading your description, it appears that you may want to use the  [responseInterceptor](https://deepchat.dev/docs/interceptors#responseInterceptor) to get the _ConversationID_ and store it in your application state and then use the [requestInterceptor](https://deepchat.dev/docs/interceptors#requestInterceptor) to add the _ConversationID_ and _channelID_ to the outgoing message.

If the above don't work, you can also try to use the [request handler](https://deepchat.dev/docs/connect#Handler) to create your own custom implementation.

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue since there has been no further communication
