### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by rishabh-ti** [OvidijusParsiunas/deep-chat#2]

**Comment by OvidijusParsiunas** [comment]
Hi @rishabh-ti, thankyou for checking out Deep Chat! This component is still under active development and is awaiting for an official release date as the library is consisntently being refactored and final features are still being added.

Websockets is something that was not planned for the initial release, but may I ask how would they help with your use-case? Deep Chat is designed to connect to APIs that use REST where users can send input data and retrieve a result based on what was sent (pretty much how most AI APIs operate). Websockets on the other hand are more useful for cases where the target service would send a message without the user's input - kind of like a human chat/notification system.

Because Deep Chat currently built for a more of a request-respond transaction system, the current focus is to use REST. However, PLEASE tell us about your use-case and how do you think websockets could be beneficial and we can consider it for a future release! Also, if you can let us know what attracted you to use Deep Chat would be very beneficial as we can always pivot to build features outside of the AI space. Thanks @rishabh-ti!

**Comment by rishabh-ti** [comment]
Hey @OvidijusParsiunas, the reason for websockets might be tech stack specific. I am using Chalice as my backend service and 
 - need to stream a large volume of response 
 - need to establish connection with the server for a fairly long period, this may also include timely getting notifications from the server.
 
The reason, why I want with deep-chat was because of proper detailed documentation with demo, plus it seemed to serve my use-case at the start.

**Comment by OvidijusParsiunas** [comment]
Deep Chat has finally been officially released. This is the first issue that I am going to tackle!
It may take some time to add the websocket functionality, update the API, documentation and examples, but I will keep this thread updated on the progress.
Thanks!

**Comment by OvidijusParsiunas** [comment]
The functionality has now been implemented. What remains is the publishing of the new npm version, API documentation and the addition of examples.

**Comment by OvidijusParsiunas** [comment]
The websocket functionality has now been published in npm version `1.1.0`.
This can be configured inside the [request](https://deepchat.dev/docs/connect#Request) object via the `websocket` property by defining it with a `boolean` true or by adding a [connection protocol](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications#creating_a_websocket_object) as a string (or multiple inside an array).

New `request` type:
{
  &nbsp;&nbsp;&nbsp;&nbsp; url: string,
  &nbsp;&nbsp;&nbsp;&nbsp; method?: string,
  &nbsp;&nbsp;&nbsp;&nbsp; headers?: {[string]: string},
  &nbsp;&nbsp;&nbsp;&nbsp; additionalBodyProps?: {[string]: any},
  &nbsp;&nbsp;&nbsp;&nbsp; <b>websocket?: boolean | string | string[]</b>
}

Example:
```
// basic
chatElement.request = {url: 'ws://localhost:8080', websocket: true};

// protocols
chatElement.request = {url: 'ws://localhost:8080', websocket: ["protocolOne", "protocolTwo"]};
```

The repo has not been updated with these details yet as I wanted to give you the opportunity to test it for your project. However the update will be coming in tomorrow.
Let me know what your thoughts are and if you find any issues.

Thanks!

**Comment by OvidijusParsiunas** [comment]
One important thing I forgot to mention, the messages sent to Deep Chat must be stringified JSONs of the [`Result`](https://deepchat.dev/docs/connect/#Result) type and the messages that will be sent from Deep Chat will be stringified JSONs described [here](https://deepchat.dev/docs/connect/) (depending on if you are sending text or file data) so you will need to parse them (e.g. JSON.parse(message)).

Illustration:

Deep Chat will be sending a string message to your server with the following format:
```{messages: [{role: 'user', text: 'message text'}]}```

When sending a message to Deep Chat - your server will need to stringify a [`Result`](https://deepchat.dev/docs/connect/#Result) type object:
```JSON.stringify({result: {text: 'Message from the server'}})```

**Comment by OvidijusParsiunas** [comment]
Hi, the repo and the [website](https://deepchat.dev/) have now been updated with the latest information for [websockets](https://deepchat.dev/docs/connect#Websocket). You can access the latest version of this feature using npm version `1.1.1`.

Thankyou for your feedback as it is what made it possible to deliver this feature :heart:! I will be closing this thread, however if you notice any issues you can still comment and I will be happy to look into them! For other matters you are more than welcome to open up new issues!

Thanyou again!

**Comment by OvidijusParsiunas** [comment]
To anyone reading this thread and using the Deep Chat version that is `1.3.0` or higher, the result object has been replaced with [`Response`](https://deepchat.dev/docs/connect#Response).
