### ISSUE TITLE
Have you seen that NASA.gov is using your project? so cool, congratz!

### ISSUE THREAD

**Issue by marioseixas** [OvidijusParsiunas/deep-chat#200]
https://www1.grc.nasa.gov/research-and-engineering/vine/petal/

https://github.com/nasa-petal/bidara-deep-chat

Very good implementation of deep-chat there, i'm gonna fork their repository and adapt to my needs.

Just want to congratulate your efforts and work from Brazil, keep it up, you are awesome, man.

Also, there is an ETA for the new deep-chat/active-chat that you keep talking in your replies?

Thanks in advance!

**Comment by OvidijusParsiunas** [comment]
WOW! That is awesome to see!!!!!!!

Credit goes to @jackitaliano, @bruffridge and other people that have been working on such an exciting endeavour!
They've been keeping me on my toes for all the recent OpenAI updates and making sure the implementation is correct!

**Comment by OvidijusParsiunas** [comment]
Granted the Deep Chat version they are using is `dev` and I've been really delaying the next release of the core version because there are A LOT of API changes (currently in `dev` version), meaning that a big part of the documentation and the YouTube videos will need to be re-done, hence there is a lot of work to do.

Also, I have recently started a new job, and am finishing up my studies for this semester, hence I haven't had much free, but my summer should be a lot more free, so to answer your question on the ETA on the next release - it will be early summer, hopefully June.

Once that is done, I should hopefully be able to start looking at the [active-table](https://github.com/OvidijusParsiunas/active-table) again and add enhancements to it.

**Comment by OvidijusParsiunas** [comment]
I have posted about this in my LinkedIn:
https://www.linkedin.com/posts/ovidijus-parsiunas-1a8a85106_petal-glenn-research-center-nasa-activity-7196873861705924609-bhHs?utm_source=share&utm_medium=member_desktop

And have shared it in X/Twitter:
https://x.com/OviSource/status/1791108622870560914

I will close this issue to try and keep the amount of open ones to a minimum, but I really appreciate you for letting me know about this and once again congratulations to the team!

**Comment by bruffridge** [comment]
Thank you @OvidijusParsiunas for all your hard work. Our chatbot would've taken so much longer to build without `deep-chat`. And congratulations on the new job!

**Comment by a-l-e-k-k** [comment]
You guys are so based

**Comment by OvidijusParsiunas** [comment]
That's what it's all about!

Also thankyou for your sponsorship @a-l-e-k-k, I couldn't find your email but you can contact me to discuss any specifics. Thankyou again!
