### ISSUE TITLE
None of the table options are working.

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [OvidijusParsiunas/deep-chat#222]
I have used **Active Table** in deep-chat. The table is showing properly but the table options like sorting, inserting etc are not working. I checked in the example you gave at https://deepchat.dev/docs/messages/HTML, even there it's not working.

<img width="717" alt="Screenshot 2024-06-20 at 16 43 38" src="https://github.com/OvidijusParsiunas/deep-chat/assets/9896335/82fdefee-fe2f-481a-a9ca-c2a305a3ddc5">

**Comment by OvidijusParsiunas** [comment]
Hi @rajeshwarpatlolla.
The issue appears to be on the [Active Table](https://github.com/OvidijusParsiunas/active-table) side as it uses the global [`document`](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction) variable to access the parent view. This becomes problematic when [Active Table](https://github.com/OvidijusParsiunas/active-table) is inside another [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM) as the [`document`](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction) variable can return incorrect data.

To note, I am the owner of the [Active Table](https://github.com/OvidijusParsiunas/active-table) project and due to my currently limited time will not be able to fix this issue. The demo is there to only help demonstrate how to insert [custom elements](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements)/[shadow elements](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM) using the [`html`](https://deepchat.dev/docs/messages/HTML/) property.

If you need a table or anything else, I would recommend checking out the [https://www.webcomponents.org/](https://www.webcomponents.org/) website.

Thankyou.
