### ISSUE TITLE
Scroll to the desired position

### ISSUE THREAD

**Issue by arreumb** [OvidijusParsiunas/deep-chat#224]
Hi, 
after deep-chat is pre-populated using initialMessages[] it shows the end of the conversation; is there a way to populate it but make it show the beginning of the conversation without using unnecessary animations? It would be really needed in  mail-client-like applications.

Thanks

**Comment by OvidijusParsiunas** [comment]
Hi @arreumb,
If you want to scroll the chat to a particular location once it has been rendered, you can do so by listening to the [`onComponentRender`](https://deepchat.dev/docs/events#onComponentRender) event, find the element that has the scrollbar (it currently has an id of `messages`) and set the [scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) property to the height that you want. E.g:

```
chatElementRef.onComponentRender = (ref) => {
  setTimeout(() => {
    ref.shadowRoot.getElementById('messages').scrollTop = 0;
  });
};
```

The reason why we use a `setTimeout` here is because the messages are not populated when [`onComponentRender`](https://deepchat.dev/docs/events#onComponentRender) is triggered, hence we should scroll after they are populated.

**Comment by arreumb** [comment]
Thanks. Without onComponentRender I wasn't able to hide the messages before to scroll top. Hiding the messages inside the event before the setTimeout was the right solution.
