### ISSUE TITLE
can't use GPT-4 or above

### ISSUE THREAD

**Issue by simonator1001** [OvidijusParsiunas/deep-chat#228]
hi, newbie question here, I tried to use model other than the default gpt3.5, such as gpt-4o and gpt-4 which seems doesn't work and still present itself as 3.5. Would appreciate if you could point me in the right direction. Million thanks in advance.

directConnection='{
    "openAI": {
      "key": "XXXXXXXXX",
      "chat": {"model": "gpt-4","max_tokens": 2000, "system_prompt": "Assist me with anything you can"}
    }
  }'

**Comment by OvidijusParsiunas** [comment]
Everything you are doing here is correct.

The actual problem is the fact that LLMs are not great at telling what exact model they are.

You can actually test this in the official [OpenAI Playground](https://platform.openai.com/playground/chat?models=gpt-4):
<img width="1491" alt="Screenshot 2024-07-11 at 06 12 06" src="https://github.com/OvidijusParsiunas/deep-chat/assets/18709577/18c4fd6c-8db9-4cd4-9d35-f2f7152727fb">
