### ISSUE TITLE
react-google-charts is not showing up using Deepchat in React Application

### ISSUE THREAD

**Issue by prabhakar1994** [OvidijusParsiunas/deep-chat#23]
Hi @OvidijusParsiunas, Hope you are doing good.

My first question is Does Deepchat supports react-google-charts ?
If yes what is correction I need to do in my code.

I am using the "data" to render the pie chart instead of response received from Axios.

`const data = [
    ["Year", "Sales", "Expenses", "Profit"],
    ["2014", 1000, 400, 200],
    ["2015", 1170, 460, 250],
    ["2016", 660, 1120, 300],
    ["2017", 1030, 540, 350],
  ];`
  
                    `<DeepChat request={{
                      handler: async (body, signals) => {
                        try {
                          const response = await axios.get(process.env.REACT_APP_API_URL + 'chat/query?text='+body.messages[0].text);
                          const htmlResponse = `<div>
                                                  <div style="margin-bottom: 10px">Here is an example chart:</div>
                                                  <Chart
                                                    className="chartbot"
                                                    chartType="PieChart"
                                                    width="100%"
                                                    height="400px"
                                                    data=${data}
                                                  />
                                                  ${chartComponent}
                                                </div>`;
                                             
                          signals.onResponse({ html: htmlResponse });
                        } catch (error) {
                          console.error(error);
                        }
                      }
                    }} />`
                    
                    
   In Elements of Console window the code renders for Chart is like below
   
   `<div>
   <div>Here is an example chart:</div>
   <chart classname="chartbot" charttype="PieChart" width="100%" height="400px" data="[[&quot;Year&quot;,&quot;Sales&quot;,&quot;Expenses&quot;,&quot;Profit&quot;],[&quot;2014&quot;,1000,400,200],[&quot;2015&quot;,1170,460,250],[&quot;2016&quot;,660,1120,300],[&quot;2017&quot;,1030,540,350]]">
[object Object]</chart>
</div>`

**Comment by OvidijusParsiunas** [comment]
Hi @prabhakar1994, if you want to embed a component inside the chat element, it MUST be a [web component](https://developer.mozilla.org/en-US/docs/Web/API/Web_components) e.g. a [`custom-element`](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements) or a [`shadow-element`](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM). The reason for this is because the component must be able to render without having any dependencies to the parent application.

Based on what I can see, _react-google-charts_ are standard react components and not web components, hence they will not be able to be rendered inside the Deep Chat component. If you need a chart, I would advise the use of [google-chart](https://www.webcomponents.org/element/@google-web-components/google-chart) components which are web components. The Deep Chat website also contains [an example](https://deepchat.dev/docs/messages/HTML#moreExamples) of how you can embed them (you may need to scroll down to find it).

To retrieve the data for the chart, you are correct to use the `handler` function and you may simply need to change your code to _something_ like this:

```
const htmlResponse = `
<div>
    <div style="margin-bottom: 10px">Here is an example chart:</div>
    <google-chart data=${JSON.stringify(data)}></google-chart>
</div>`
```

Let me know if this helps. Thanks!

**Comment by prabhakar1994** [comment]
@OvidijusParsiunas Absolutely, I have tried that way too But no luck.  Still getting the `[Object Object]`

**Comment by prabhakar1994** [comment]
Hi @OvidijusParsiunas, Thank you for your suggestion. I found something like this,

The Chart component is unable to bind in UI in run time. So its not able to render. I tried couple of react render methods to parse the HTML. But those are also not working. So I did a work around. The below the code for that.

`<DeepChat 
                      style={{
                        borderRadius: "10px",
                        position: "fixed",
                        bottom: "0",
                        right: "7%",
                        zIndex: 1,
                        height: "calc(100vh - 98px)",
                        width: "96vw"
                    }}
                    avatars={{
                        default: { styles: { position: "left" } },
                        ai: { src: "/profile/images/openAIGreyLogo.svg" },
                        user: { src: "/profile/images/23735.png" },
                    }}
                    messageStyles={{
                        default: {
                        shared: {
                            innerContainer: { width: "95%" },
                            bubble: {
                            maxWidth: "100%",
                            backgroundColor: "unset",
                            marginTop: "10px",
                            marginBottom: "10px",
                            fontSize: "1rem",
                            },
                        },
                        user: {
                            bubble: {
                            marginLeft: "0px",
                            color: "black",
                            },
                        },
                        ai: {
                            outerContainer: {
                            backgroundColor: "rgba(247,247,248)",
                            borderTop: "1px solid rgba(0,0,0,.1)",
                            borderBottom: "1px solid rgba(0,0,0,.1)",
                            },
                        },
                        },
                    }}
                    textInput={{ placeholder: { text: "Welcome to DocuFlow..!" } }}
                    audio={true}
                    images={true}
                    gifs={true}
                    camera={true}
                    microphone={true}
                    mixedFiles={true}
                      request={{
                        url: process.env.REACT_APP_API_URL + 'chat/query',
                        handler: async (body, signals) => {
                          try {
                            const response = await axios.get(process.env.REACT_APP_API_URL + 'chat/query?text=' + body.messages[0].text);
                            if (response.data.type === "text") 
                            {
                              signals.onResponse({ text: response.data.type });
                            } else {
                              this.setState({ chartData: data, chartType: "PieChart", isChartEnabled: true });
                              signals.onResponse({ text: response.data.type });
                            }
                          } catch (error) {
                            console.error(error);
                          }
                        },
                      }}
                    >
                      {this.state.isChartEnabled && (
                        <Chart
                          className="chartbot"
                          chartType={this.state.chartType}
                          width="100%"
                          height="auto"
                          data={this.state.chartData}
                        />
                      )}
                    </DeepChat>`
                    
                    Binding Chart to element to Deepchat and populating based on the state. But a new issue came up. The previous chart history erases automatically when the  new request we enter. Would appreciate your suggestions on this.

**Comment by OvidijusParsiunas** [comment]
Hi @prabhakar1994, the reason why your last approach works is because you have embedded the chart as a [slot](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_templates_and_slots), hence your React app still holds a reference to it and it appears to work ok. However, slots in Deep Chat are used for the [intro panel](https://deepchat.dev/docs/introPanel), hence when you send the first message it disappears.

You need to use the `html` response property if you want the chart to appear in the message bubbles. I am noticing that you are still using `<Chart` in the syntax. If you are using `react-google-charts` this will not work and you must instead use the [google-chart](https://www.webcomponents.org/element/@google-web-components/google-chart) component that I mentioned above.

I am currently not beside my computer at the moment, but I can whip up a quick example on how to do this in React later when I get back home (in around 4 hours). If you have already tried to use [google-chart](https://www.webcomponents.org/element/@google-web-components/google-chart) may I see your code to help me identify any issues.

Thanks!

**Comment by OvidijusParsiunas** [comment]
Here is a [Code Sandbox](https://codesandbox.io/s/deep-chat-react-chart-ztsgrd?file=/src/App.tsx) that has a working chart inside Deep Chat.

Please note that you should install _@google-web-components/google-chart_ version <b>5.0.3</b> and not higher as newer versions use a [`safevalues`](https://github.com/GoogleWebComponents/google-chart/commit/69e7598536b81886ab84726cf00b6d81307b210a) library which can break the React build, so your `package.json` should have this:

`"@google-web-components/google-chart": "5.0.3"`

To tailor the Code Sandbox example to your case, you should use the following syntax:

```
<DeepChat
  request={{
    url: process.env.REACT_APP_API_URL + "chat/query",
    handler: async (body, signals) => {
      try {
        // const response = await axios.get(process.env.REACT_APP_API_URL + 'chat/query?text='+body.messages[0].text);
        const data = [
          ["Year", "Sales", "Expenses", "Profit"],
          ["2014", 1000, 400, 200],
          ["2015", 1170, 460, 250],
          ["2016", 660, 1120, 300],
          ["2017", 1030, 540, 350],
        ];
        const htmlResponse = `
                <div>
                  <google-chart
                    style="width: 220px; height: 200px"
                    data='${JSON.stringify(data)}'
                    options='{"legend": "none"}'>
                  </google-chart>
                </div>
                `;
        signals.onResponse({ html: htmlResponse });
      } catch (error) {
        console.error(error);
        signals.onResponse({ error: "error" });
      }
    },
  }}
/>;
```

I am going to update the website documentation to add a live link to the sandbox, let me know if this helps you.

Thanks!

**Comment by prabhakar1994** [comment]
Hi @OvidijusParsiunas. Awesome its worked. Thank you so much. So just a missing piece. Deepchat doesn't support any other Chart library except google-chart ?

**Comment by OvidijusParsiunas** [comment]
The `html` property only supports [web components](https://developer.mozilla.org/en-US/docs/Web/API/Web_components) and not framework related components. So it supports all chart libraries that can be used as [web components](https://developer.mozilla.org/en-US/docs/Web/API/Web_components).

The [www.webcomponents.org](www.webcomponents.org) and [awesome-web-components repo](https://github.com/web-padawan/awesome-web-components) are great places to look for web components, but there are many more out there if you search GitHub.

Also, you can create your own web components using plain JavaScript, here is a quick [guide](https://javascript.plainenglish.io/introduction-to-web-components-in-javascript-create-a-hello-world-web-component-e624874ec3b1) for this. There are also great web component frameworks such as [Lit](https://lit.dev/) that can help you create web components with ease.

I will be closing this issue since the original problem has been fixed, however if you have any further questions feel free to comment below or create a new issue. Thanks!

**Comment by prabhakar1994** [comment]
Hi @OvidijusParsiunas, Appreciate your help. It really worked. Thank you so much. I have a quick question. How do we make the chart downloaded. Do you have any idea ?

**Comment by OvidijusParsiunas** [comment]
Hey @prabhakar1994, I have looked at their API and the only solution to export a chart that I found was to first convert it into an image, then probably use standard javascript to do it. Link to example conversion logic can be found [here](https://developers.google.com/chart/interactive/docs/printing).

To do all of this, you will probably need to create your own web component (using the links in my previous comment) and wrap the chart inside it along with the required export code. This is definitely not easy, but one way that I think will work.
