### ISSUE TITLE
Advice needed for submitUserMessage

### ISSUE THREAD

**Issue by ki-zeitalter** [OvidijusParsiunas/deep-chat#244]
Hi DeepChatTeam!

I'm struggling to get submitUserMessage to work. Basically it doesn't seem to do anything at all and I'm not sure why.

So I made a very simple example to show what I'm doing:

```
import {DeepChat as DeepChatCore} from 'deep-chat';
import {DeepChat} from 'deep-chat-react';
import {useEffect, useRef, useState} from "react";
import './style.css';

export const App = () => {
  const [buttonmsg, setButtonmsg] = useState("")

  const deepChatRef: React.RefObject<DeepChatCore> = useRef(null);

  useEffect(() => {
    if (deepChatRef && buttonmsg != "") {
      deepChatRef.current.submitUserMessage({text: buttonmsg})
    }
  }, [buttonmsg])

  return (
    <div className="App">
      <h1>Deep Chat</h1>
      <DeepChat
        ref={deepChatRef}
        demo={true}
        style={{ borderRadius: '10px' }}
        textInput={{ placeholder: { text: 'Welcome to the demo!' } }} 
      />

      <button onClick={() => setButtonmsg("Hi this is a message submitted by a button!")}>Click me!</button>
    </div>
  );
};

```

In my real world code the message even seems to be sent to the back-end but the response is not shown at all. In my simple example it is not visible as well.

Maybe I'm doing something horribly wrong so I would be glad if you could give me an advice!

Thanks!

**Comment by OvidijusParsiunas** [comment]
Hi @ki-zeitalter.
The problem appears to stem from the fact that you are updating your React state, which causes a re-render of the component - which also re-renders the Deep Chat component. So in essence, the method does work fine, however Deep Chat is re-rendered directly after it is updated, hence it looks like nothing is happening. You will also sometimes see that Deep Chat does not refresh, that is because it has lost the reference to the original component.

I have fixed your setup to reflect this:
```
export default function App() {
  const deepChatRef: React.RefObject<DeepChatCore> = useRef(null);


  function submit(text: string) {
    if (deepChatRef.current ) {
      deepChatRef.current.submitUserMessage({text})
    }
  }
  
  return (
    <div className="App">
      <h1>Deep Chat</h1>
      <DeepChat
        ref={deepChatRef}
        demo={true}
        textInput={{ placeholder: { text: 'Welcome to the demo!' } }} 
      />
      <button onClick={() => submit("Hi this is a message submitted by a button!")}>Click me!</button>
    </div>
  );
}
```

Long story short, you should try not to use `useState` in the same component that Deep Chat is being used in.

I have outlined alternative solutions in the following [comment](https://github.com/OvidijusParsiunas/deep-chat/issues/61#issuecomment-1839452308). You can also find other alternative solutions in the same [issue](https://github.com/OvidijusParsiunas/deep-chat/issues/61)

The Deep Chat [Playground](https://deepchat.dev/playground) is actually using [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to persist messages and selected configuration. You can check the code [here](https://github.com/OvidijusParsiunas/deep-chat/blob/fb8811edce4caaa7eebd0f93ccb76ca1118f6ee5/website/src/pages/playground.jsx#L46). Another solution is the use of [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) for temporary storage.

Hopefully this helps you. Thanks.
