### ISSUE TITLE
Property init from backend taking too long ignored [help wanted]

### ISSUE THREAD

**Issue by Thomas-Lacomblez** [OvidijusParsiunas/deep-chat#248]
Hello,

I am using deep-chat to setup a chatbot. I am trying to set the introMessage property from a variable. This variable is set from a http request to my backend on my page load/component init (I am using angular) and I realise that even when the request is ok the introMessage variable I am using is correctly set (I use console.log() to print the response and everything is correct/what's it's suppose to be) but nothing is shown in the chat.

I checked if this was an issue in my code but when I set the variable with hardcoded  value it works perfectly. I Even hardcoded the response on my backend side so it response instantly and it does work but when the variable use for the property isn't set instantly when the deep-chat is loaded then the values is like ignores/not updated.

Is that a bug ? Or is expected to not updated the properties values After the chat is init ?
Does anyone already to init the introMessage/History with the backend side and know a way to do that ?

The only way to do what I need would be to do a loading screen myself and load/show the chat once the introMessage in set from the backend but I would like to know if there weren't any other solutions 

TL

Edit : I am sure I select [Help wanted] label but it seems not to have worked for some reason.

**Comment by OvidijusParsiunas** [comment]
Hey @Thomas-Lacomblez.
Currently the introduction/history values are expected to be set immediately when the chat loads. If they are not, I would recommend you to only display/render the chat when they have been loaded.

However, I am actually working on a feature that would allow the history to be loaded (instead of being set on start). The only downside is that you can't download the [`introMessage`](https://deepchat.dev/docs/messages/#introMessage). However if you need it, then simply add it to your returned history.

Follow this feature's progress in the following [issue](https://github.com/OvidijusParsiunas/deep-chat/issues/158).
