### ISSUE TITLE
[Help wanted]One page with another binding variable outside of the chat component

### ISSUE THREAD

**Issue by yeungxh** [OvidijusParsiunas/deep-chat#250]
<img width="515" alt="2024-08-18_202701" src="https://github.com/user-attachments/assets/b2ef0d5c-22f8-45e9-a7d4-d49606ae4c5c">

I'm using deep-chat in vue2, as you can see, once there's another variable history.length, once its value changes, the deep-chat messages will be cleared.
I'm using Interceptor as below

<img width="429" alt="2024-08-18_203333" src="https://github.com/user-attachments/assets/22b35fc8-0edb-40c6-aca3-bfa85b9d8781">

**Comment by OvidijusParsiunas** [comment]
Hi @yeungxh.
It appears that this is caused by the state management in Vue 2. Basically when the state changes inside it, all the markup incl. the Deep Chat component gets re-rendered.

This is a common state management pattern in most UI frameworks, incl. React where I have specifically addressed this problem in the following [comment](https://github.com/OvidijusParsiunas/deep-chat/issues/61#issuecomment-1839452308). The solution for this in Vue 2 is quite similar as it behaves similarly.
I would also advise you to checkout the following question in [Stack Overflow](https://stackoverflow.com/questions/69811786/prevent-vue-js-re-rendering-child-components).

**Comment by OvidijusParsiunas** [comment]
Unfortunately because this issue is to do with the particular setup of your component structure in Vue, it is out of Deep Chat's hands. Therefore, I will close this issue.

However, if you were able to find specific ways to overcome your issue, please share it in the comments below. Thanks!
