### ISSUE TITLE
`request.body.attachments` is not defined in `requestInterceptor` when `files_tool_type` is set to a function

### ISSUE THREAD

**Issue by bruffridge** [OvidijusParsiunas/deep-chat#281]
When I upload a `.docx` file ...

```
async function requestInterceptor(request) {
    if (newFileUploads.length > 0) {
      newFileIds = request.body.attachments.map(attachment => attachment.file_id);

      handleFileUploads(newFileIds, newFileUploads);
    }

    return request;
  }
```

... `request.body.attachments` in requestInterceptor is defined when setting `files_tool_type` to a string value.

```
<deep-chat
  id="chat-element"
  directConnection={{
    openAI: {
      key: key,
      validateKeyProperty: key ? false : true, // if apiKey is not null it has already been validated.
      assistant: key ? {
        assistant_id: asstId,
        new_assistant: asstConfig,
        thread_id: threadId,
        load_thread_history: false,
        files_tool_type: "file_search",
        function_handler: handleFuncCalling
      } : null
    }
  }}
  requestInterceptor={requestInterceptor}
...
```

but is undefined when setting it to a function definition.

```
function fileTools(fileNames) {
    return "file_search";
  }

<deep-chat
  id="chat-element"
  directConnection={{
    openAI: {
      key: key,
      validateKeyProperty: key ? false : true, // if apiKey is not null it has already been validated.
      assistant: key ? {
        assistant_id: asstId,
        new_assistant: asstConfig,
        thread_id: threadId,
        load_thread_history: false,
        files_tool_type: fileTools,
        function_handler: handleFuncCalling
      } : null
    }
  }}
  requestInterceptor={requestInterceptor}
...
```

**Comment by OvidijusParsiunas** [comment]
Hi @bruffridge.
The `attachments` property should not be displayed in the `request.body.attachments` path and instead it should be `body.thread.messages[anyIndex].attachments`. Example image:
![Screenshot 2024-10-12 at 14 23 30](https://github.com/user-attachments/assets/d6a2f027-0c06-404b-84cd-fc3402f94d80)
This is pretty much how the code is configured to work [here](https://github.com/OvidijusParsiunas/deep-chat/blob/fbbc66528b385cf39c0aca18ad27549fe484a00c/component/src/services/openAI/openAIAssistantIO.ts#L168). I have tested it with both the `files_tool_type` property value set as a `string` and as a `function` and the result displays as above.

Hence, I am more concerned on how did you get it to be displayed in the `request.body.attachments` path. Can you please double check if this is still the case for you and if so, it could perhaps be something weird caused by the `handleFuncCalling` function. Any more details on this would be helpful. Thanks!

**Comment by bruffridge** [comment]
My `request.body` object doesn't contain `assistant_id` or `thread` either. It only contains `attachments`, `content`, and `role`set to "user".

**Comment by OvidijusParsiunas** [comment]
Hey @bruffridge.

For request messages, when the `thread` property is defined the `assistant_id` does not need to be sent along with the body as it will automatically use the assistant associated with the thread. Additionally the `thread_id` is not sent in the body as it instead needs to be used as a url subpath instead: `https://api.openai.com/v1/threads/{thread_id}/messages`.
The request logic uses the [`createMessage`](https://platform.openai.com/docs/api-reference/messages/createMessage) API.

May I ask why do you need these properties in the body?

Thanks!

**Comment by bruffridge** [comment]
I don't need them, just noticing a difference between your `request.body` inside `requestIntercepter` and what I'm seeing. The main issue I'm still having is not seeing the attachments when `file_tools_type` is set to a function that returns a string.

**Comment by bruffridge** [comment]
Tracked down the cause. It's actually the same as the last bug I reported. Stringify removes the function from the config object on this line.

https://github.com/OvidijusParsiunas/deep-chat/blob/main/component/src/services/openAI/assistant/openAIAssistantIO.ts#L22

**Comment by OvidijusParsiunas** [comment]
Hey @bruffridge.
Thankyou for your contribution! I have merged your changes!
The new code has been published in `deep-chat-dev` and `deep-chat-react-dev` package versions `9.0.201`. Let me know if this works for you. Thanks!

**Comment by bruffridge** [comment]
It works now thank you.
