### ISSUE TITLE
Error: Please define the function_handler property inside the openAI object.

### ISSUE THREAD

**Issue by bruffridge** [OvidijusParsiunas/deep-chat#294]
Package: `deep-chat-dev`
Version: `9.0.199`
Location: `directionConnection.openAI.assistant.function_handler`

What happened:
Sending a message to invoke function calling results in the error message, "Please define the function_handler property inside the openAI object."

I tracked down the source of the issue, PR on its way to fix this.

**Comment by OvidijusParsiunas** [comment]
Hey @bruffridge.

I realised this issue is also in other OpenAI related `function_handler` code. I have instead updated all of the related classes based on the previous way they were implemented in the following [commit](), hence I will close your PR.

Thankyou for bringing this to my attention and I have released the latest updates in `deep-chat-dev` and `deep-chat-react-dev` packages version `9.0.200`. Please let me know if they work for you. Thankyou!
