### ISSUE TITLE
html can't be styled

### ISSUE THREAD

**Issue by Morriz** [OvidijusParsiunas/deep-chat#299]
Hi, thanks first of all for all the good work. However, I am hitting the inability to override the resulting html with css. It would surely be beneficial to refactor that part, as not being able to style bubbles (or anything for that part) is a big omission imo...

I would try to give it a whirl myself if I had the time and the expertise (I am a react specialist and not familiar with web components).

I surely hope it is not the web component approach that makes this impossible, but I suspect it is. Is there no hope for being able to hack internal html with outside css? If that is the case I am not a big fan of web components...

**Comment by OvidijusParsiunas** [comment]
Web components is an umbrella term for a variety of different type of elements, e.g. [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM), [custom elements](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements) etc.
shadow DOM is not part of the main DOM, meaning its style will not inherit the one placed in the main DOM (parent app). Custom elements exist alongside the main DOM and they will inherit the parent style.

Due to the beauty of the ability to inject a component inside any application and achieve the advertised result - Deep Chat utilises the shadow DOM. Ofcourse, the downside of this is the difficulty in being able to style its internals.
The Deep Chat [website](https://deepchat.dev/) provides many ways to [style](https://deepchat.dev/docs/styles) the chat, and in reference to your message you can style the bubbles [here](https://deepchat.dev/docs/messages/styles). We also provide [examples](https://deepchat.dev/examples/design) to help achieve what you need.

You can also use the [`auxiliaryStyle`](https://deepchat.dev/docs/styles#auxiliaryStyle) property to override the existing css (however we recommend using the approach above).
E.g. 
```js
auxiliaryStyle = `
    .user-message {
        background-color: yellow;
    }`
```

Let me know if this helps. Thanks!

**Comment by Morriz** [comment]
I now know what to do :) Thanks for the elaborate reply!

**Comment by Morriz** [comment]
After tinkering with this stuff for waaaaay too long I came to understand that web components the way they are implemented here are making it impossible to style stuff iteratively from a useful dev experience perspective.

@OvidijusParsiunas maybe I missed something? How can we use breakpoints, dark mode, all the goodies etc, to style the container? is that doable with `auxiliaryStyle`

**Comment by OvidijusParsiunas** [comment]
I agree that editing the styling of Shadow Elements is inconvenient, but as mentioned in my earlier comment this in a way is by design and not much can really be done about it.

The [`auxiliaryStyle`](https://deepchat.dev/docs/styles#auxiliaryStyle) property can be used to define relatively advanced css, such as media queries:
```js
auxiliaryStyle = `
    @media only screen and (max-width: 600px) {
      .ai-message {
            background-color: yellow;
        }
    }`
```

However I am not fully sure about the extent to how many _advanced_ css features are supported as it is entirely up to how the [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM) works and not necessarily how Deep Chat is implemented.

Apologies for not being able to do much more.
