### ISSUE TITLE
loading bubble styles are overwritten by inline styles

### ISSUE THREAD

**Issue by bruffridge** [OvidijusParsiunas/deep-chat#300]
`deep-chat-dev` v9.0.201
Not sure when this bug was introduced, but this code used to work. We wanted the padding to be different on the loading bubble. Now the padding on the loading bubble is `.42em ...` instead of `0.6em ...`. I tried adding the `!important` flag but it looks like it is being stripped.

![Screenshot 2024-11-14 at 9 57 14 AM](https://github.com/user-attachments/assets/3f3e55f7-247c-4246-8a15-4db3ed970128)

```
messageStyles={{
    default: {
      shared: {
        bubble: {
          maxWidth: "75%",
          borderRadius: "1em",
          padding: ".42em .7em"
        }
      },
      ai: {
        bubble: {
          color: "var(--text-primary-color)",
          backgroundColor: "var(--ai-message-background-color)",
        }
      },
      user: {
        bubble: {
          color: "white",
          backgroundColor: "var(--user-message-background-color)",
        }
      }
    },
    loading: {
      bubble: {
        padding: "0.6em 0.75em 0.6em 1.3em !important"
      }
    }
  }}
```

**Comment by OvidijusParsiunas** [comment]
Hey @bruffridge.
The loading property in [`messageStyles`](https://deepchat.dev/docs/messages/styles/#messageStyles) has been refactored since the introduction of the new `loadHistory` function that is related to the following [issue](https://github.com/OvidijusParsiunas/deep-chat/issues/158). Because this has yet not been released it is not part of the documentation.

However, I should have added backwards compatibility or some heads-up in the issue that this has taken place, for this I apologise.

The new type is as follows where [MessageElementsStyles](https://deepchat.dev/docs/messages/styles/#MessageElementsStyles) is the already existing type:
```
export interface MessageStyles {
  ...
  loading?: LoadingMessageStyles;
}

export interface LoadingMessageStyles {
  message?: LoadingStyles;
  history?: LoadingHistoryStyles;
}

export interface LoadingHistoryStyles {
  full?: LoadingStyles;
  small?: LoadingStyles;
}


export interface LoadingStyles {
  styles?: MessageElementsStyles;
  html?: string;
}
```

Relating it back to your example your `loading` property's implementation should be as follows:
```
loading: {
  message: {
    styles: {
      bubble: {
        padding: '0.6em 0.75em 0.6em 1.3em'
      }
    }
  }
}
```

I have also added backward compatibility for this in `deep-chat-dev` and `deep-chat-react-dev` package versions `9.0.202`.

Let me know if this works for you.
Thankyou!

**Comment by bruffridge** [comment]
That worked, thanks so much.

**Comment by OvidijusParsiunas** [comment]
It appears I introduced a small bug where an error is thrown when the `loading` property is not set.
I have fixed this in `deep-chat-dev` and `deep-chat-react-dev`package versions 9.0.204.
Apologies for the inconvenience.
Thankyou!
