### ISSUE TITLE
Bug with Svelte 5: Attributes need to be JSON stringified in order to work

### ISSUE THREAD

**Issue by uwemaurer** [OvidijusParsiunas/deep-chat#312]
I tried deep-chat with svelte 5 and got it to work. 
However all attributes need to be set as strings not objects, otherwise it gives errors.

for example this example (working fine with svelte 4)

```
<deep-chat
    demo={true}
    textInput={{placeholder:{text: "Welcome to the demo!"}}
    history={history}
  ></deep-chat>
```

gives this error with svelte 5
```
VM96:1 Uncaught SyntaxError: Unexpected token 'o', "[object Obj"... is not valid JSON
    at JSON.parse (<anonymous>)
    at App (App.svelte:19:73)
```

When I change it to this:
```
<deep-chat
    demo={true}
    textInput={JSON.stringify({placeholder:{text: "Welcome to the demo!"}})}
    history={JSON.stringify(history)}
  ></deep-chat>
```

then it works.

It would be great if the deep chat component would also work like in svelte 4 with normal objects as attributes.

Here is the example I used:  https://stackblitz.com/edit/deep-chat-svelte-5-bug?file=src%2FApp.svelte

**Comment by OvidijusParsiunas** [comment]
Hi @uwemaurer.
Thankyou for letting me know about this! It seems like a serious bug, I will investigate this!

**Comment by OvidijusParsiunas** [comment]
Update:

The way properties are passed into custom elements in Svelte 5 seems to be different than the previous version.
I don't have much more time today, but I will investigate this tomorrow.

Thanks!

**Comment by OvidijusParsiunas** [comment]
After more investigation, it turns out that there was a bug introduced into Svelte in the following [PR](https://github.com/sveltejs/svelte/pull/13337).

There is another [PR](https://github.com/sveltejs/svelte/pull/14508) that has been raised to fix it which should hopefully fix that error.

All we can do at the moment is wait for that PR to be merged and the code released in the newest version of Svelte.

We'll have to keep monitoring that PR until that happens.

Thankyou!

**Comment by OvidijusParsiunas** [comment]
The changes have now been merged.

Deep Chat should work as expected in Svelte version `5.11.0+`.

**Comment by uwemaurer** [comment]
Great! Thank you for investigating this!
