### ISSUE TITLE
If message is added in a custom handler the order is not preserved

### ISSUE THREAD

**Issue by arielmoraes** [OvidijusParsiunas/deep-chat#324]
I'm using a custom handler to send messages to my backend and trying to add some actions for each response, but if messages are added inside the handler and after calling the `onResponse` from `Signals` the order is not preserved.

Simple code to show what is stated above:

```ts
signals.onResponse({
  text: 'I should appear before'
});

this.deepChat.addMessage({
  text: 'I should appear after'
})
```

The result is:
![image](https://github.com/user-attachments/assets/9bcf0c8c-14a9-41c6-b174-aa8041e8af04)

Another point is that added messages have the avatar visibility set to hidden.

**Comment by OvidijusParsiunas** [comment]
Hi @arielmoraes.
I am trying to reproduce your issue, but don't seem to be able to get it on my end. Could perhaps share some more of your configuration.
The way I am testing this is by first triggering the [`onResponse`](https://deepchat.dev/docs/connect#Signals) signal and then automatically adding a message via [`addMessage`](https://deepchat.dev/docs/methods#addMessage) method (which is triggered 3 seconds later). Here is my React code, let me know if something here may be unclear:
```
export default function App() {
  const reference = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setTimeout(() => {
      if (reference.current) {
        (reference.current.children[0] as DeepChatCore).addMessage({text: 'I should appear after'})
      }
    }, 3000);
  }, []);
  
  
  return (
    <div ref={reference}>
      <DeepChat
        connect={{
          handler: (_, signals) => {
            signals.onResponse({
              text: 'I should appear before',
            });
          },
        }}
       />
    </div>
  );
}
```

There have been a lot changes made to the recent development packages, there is a chance your issue could have been fixed there. Would you mind trying out either `deep-chat-dev` or `deep-chat-react-dev` version `9.0.223` to see if the messages appear in the correct way. These packages work exactly the same as the core ones except their names are different.

Let me know if this works.
Thankyou!

**Comment by OvidijusParsiunas** [comment]
I re-read your problem one more time and can see that I was reproducing it incorrectly.

Unfortunately now I am not beside my computer and will not get to it until tomorrow after work (I am in JST time). However I am certain that once onResponse is triggered, there's likely an async operation that takes place, whereas addMessage does not have one. Is there any chance you could place your addMessage in a setTimeout with 0 milliseconds to see if it helps. Thanks!

**Comment by arielmoraes** [comment]
Actually you have to call addMessage on the handler itself. Outside it works as expected.

**Comment by arielmoraes** [comment]
@OvidijusParsiunas by using the setTimeout the order is respected, is there a better way without resorting to setTimeouts? For me it seems hacky, maybe wrap the addMessage in a Promise?

**Comment by OvidijusParsiunas** [comment]
Hi @arielmoraes.
I did a bit of investigation and found that `onResponse` is asynchronous because its internal logic handles the [`responseInterceptor`](https://deepchat.dev/docs/interceptors#responseInterceptor) which can be optionally made asynchronous by the users. Due to the fact that [`responseInterceptor`](https://deepchat.dev/docs/interceptors#responseInterceptor) can dynamically return a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), it makes it difficult to define a consistent response type for `onResponse` (whether it should be async or not), hence for consistency I will keep it asynchronous.

One thing that I forgot to say earlier is that because `onResponse` returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), you can simply use `.then` to know exactly when to proceed with calling further logic. Or you can use `await` to wait for the `onResponse` to finish.

E.g:
```
handler: (body, signals) => {
  signals.onResponse({text: 'I should appear before'})
    .then(() => {
      this.addMessage({text: 'I should appear after'});
    });
},
```
```
handler: async (body, signals) => {
  await signals.onResponse({
    text: 'I should appear before',
  });
  this.addMessage({text: 'I should appear after'});
}
```

It is totally my fault that I didn't make this behaviour clear and I will update the `onResponse` type and the documentation accordingly. The new `onResponse` TypeScript type is going to be available in `deep-chat-dev` and `deep-chat-react-dev` package versions `9.0.224`.

Thankyou for letting me know about this.

I hope this helps!

**Comment by arielmoraes** [comment]
Indeed that's only a typing issue, I've added an await without even bumping the version and it worked. Only a lint hint appears.

![image](https://github.com/user-attachments/assets/c9a23027-02b0-449d-a795-d38644d80b51)

I appreciate your support.
