### ISSUE TITLE
LlamaIndex OpenAI Assistant Agent Support

### ISSUE THREAD

**Issue by JanFschr** [OvidijusParsiunas/deep-chat#40]
I think the integration / connection of https://gpt-index.readthedocs.io/en/stable/examples/agent/openai_assistant_agent.html would be great addition to this.

**Comment by OvidijusParsiunas** [comment]
Hi @JanFschr. I'm not quite sure what you mean by integration / connection.

If I am correct - LlamaIndex is a backend python framework for LLMs, so it doesn't expose an API that the UI can connect to. Furthermore Deep Chat [direct connection](https://deepchat.dev/docs/directConnection/) properties focus on connecting to existing live services so that developers would not need to create a backend and do everything from the browser, which is a category that LlamaIndex does not fit.

Could you maybe elaborate a little bit more about your suggestion in-case I misunderstood something. Thanks!

**Comment by JanFschr** [comment]
You are absolutely correct, I assumed LlamaIndex exposes a API by default. 

I will follow your advice and implement the service based on the templates by myself

**Comment by OvidijusParsiunas** [comment]
Happy to hear. I will close this issue.
