### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Energiz3r** [OvidijusParsiunas/deep-chat#56]
Hey. I'm trying to implement a dark mode in my React app, but changes to the style object passed to the component aren't updated / aren't stateful internally. The best I'm able to do is unmount and remount the entire component, but even that is imperfect, not to mention requires pulling out all the state management so the conversation survives the remounting.

Anyone have any tips or workarounds?

While I'm here - any word on support for customisation using tailwindcss? A way to (statefully) pass additional classnames to the various elements would be great

**Comment by OvidijusParsiunas** [comment]
Hey @Energiz3r!
The easiest way to switch between dark/light chat mode in the same session is to define two Deep Chat components and then switching between them via the use of an if statement. Ofcourse the chat messages would need to be persisted (in an outer component or other means of storage for your app) and then referenced inside the [`initialMessages`](https://deepchat.dev/docs/messages/#initialMessages) property. To help keep track of state, I would advise you to use the [`onNewMessage`](https://deepchat.dev/docs/events#onNewMessage) event or the [`getMessages`](https://deepchat.dev/docs/methods#getMessages) method.
The best reference for this is the [Playground](https://deepchat.dev/playground) website which facilitates the switching between the light/dark modes. The code for this is located in the [playgroundChatComponent.js](https://github.com/OvidijusParsiunas/deep-chat/blob/main/website/src/pages/playground/chat/playgroundChatComponent.js) file.

I am considering other potential ways to allow users to switch between different styling, however because it is a web component, the options are quite limited.

Let me know if this works for you.

In regards to tailwindcss, this framework does not actually affect the Deep Chat component as it is a shadow element, hence the ability to support it is quite limited. Could you elaborate on what you mean by _"A way to (statefully) pass additional classnames to the various elements would be great"_, thanks!

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue, however if you have any more questions relating to the discussion above feel free to comment below, for anything else - create a new issue. Thanks!

**Comment by OvidijusParsiunas** [comment]
I have also experienced issues in React where Deep Chat styling would remain the same even if the state has changed. The code in the [playgroundChatComponent.js](https://github.com/OvidijusParsiunas/deep-chat/blob/main/website/src/pages/playground/chat/playgroundChatComponent.js) (used in the [Playground](https://deepchat.dev/playground)) was what worked for me.
It is interesting that you are using a spread operator to define your properties, perhaps React tracks them differently.

I have previously considered adding an explicit property that would allow the component styling to be changed between two modes. But the problem that I ran into very quickly was that every element in the component already has multiple customization properties, so I would need to create another large interface or multiple smaller interfaces that could be used for an alternate styling mode which pretty much doubles the API complexity and makes the component harder to maintain. Therefore I recommend a more straightforward solution of just switching between two components.

I understand that this may not be ideal, hence I am still exploring other options that would allow easier mode switching.
