### ISSUE TITLE
Custom errors handling

### ISSUE THREAD

**Issue by devpulse01** [OvidijusParsiunas/deep-chat#58]
Hey Ovidijus,

Hope you're doing well. As I continue integrating deep-chat into my app, I've come across a couple of challenges related to error handling and logging.

**Custom error handling**: I'm on the lookout for a method to catch and manage errors that might pop up with the public deep-chat methods. The current setup doesn't seem to offer a way for custom error handling. It would be awesome if the methods could throw errors that I can then catch and handle in my own code.

**Custom logging**: On another note, I have a custom logger in my application. I'm interested in integrating this with the deep-chat methods. Is there a way to replace the default logging with my own logger?

Thank you!
Best

**Comment by OvidijusParsiunas** [comment]
Hi @devpulse01.

The component has been intentionally set up to never _throw_ errors in order to make it safe to use and to prevent users from having to use error boundaries. However if you would like to monitor errors, I can add a new event that would be emitted when there is an error. Could you elaborate on what kind of errors are you interested in? Is it service errors?

In regards to logging, what kind of things would you like to log?

**Comment by devpulse01** [comment]
Hey Ovidijus,

Thank you for your reply.

**Errors:**
If you can add a new event that is emitted in case of errors, that would be perfect. Yes, it's for service errors (e.g., wrong API key, wrong service parameters, etc.).

**Logging:**
I think both are related. I would love to handle errors on my own and thus be able to log them within my users' context.

**Comment by OvidijusParsiunas** [comment]
I'll implement a new event and update this thread when it is available to be used.
