### ISSUE TITLE
how to use textToSpeech?

### ISSUE THREAD

**Issue by wysstartgo** [OvidijusParsiunas/deep-chat#65]
I just want to know how to use textToSpeech,when I use as below,it does not work!
```
<!-- This example is for Vanilla JS and should be tailored to your framework (see Examples) -->

<deep-chat
  textToSpeech='{"volume": 0.9}'
  introMessage='{"text": "Send a message to hear the response."}'
  style="border-radius: 8px"
  demo="true"
></deep-chat>
```

**Comment by OvidijusParsiunas** [comment]
Hi @wysstartgo.
Text To Speech will activate only for new messages - so the [`introMessage`](https://deepchat.dev/docs/messages/#introMessage) and [`initialMessages`](https://deepchat.dev/docs/messages/#initialMessages) will not produce audio.
In your example, if you type in a message and submit, the new response should have audio.

If it does not, then there could perhaps be a problem with the browser you are using.

- Check that your computer volume is on.
- Deep Chat uses the native [speechSynthesis](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis) API to create audio which is supported by most modern browsers, check [here](https://caniuse.com/speech-synthesis) if your browser is supported.
- Check the following [demo website](https://mdn.github.io/dom-examples/web-speech-api/speak-easy-synthesis/) to see if speech synthesis works for you (on the same browser you use Deep Chat). If the demo website works for you and Deep Chat does not - then I will investigate the problem, otherwise the problem is unfortunately with your browser.

**Comment by wysstartgo** [comment]
okay，I will try it again later，thanks！

**Comment by wysstartgo** [comment]
It works well，thanks!

**Comment by OvidijusParsiunas** [comment]
I'm happy to hear it works!
